### ISSUE TITLE
Sometimes you land immediately after jumping.

### ISSUE THREAD

**Issue by ThePokemonkey** [luigidasonic/RobloxTAS#3]
Holding w+Space and frame advancing can cause you to jump and then immediately land, which has the effect of delaying your jump by a couple frames at random times.

video: https://streamable.com/jth8b2

**Comment by mikpam12** [comment]
im pretty sure that's just an animation bug

if you hold w and space and let go before you frame advance, the jump animation is triggered but you dont actually jump
